apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-project
  namespace: flask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: flask.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-project
                port:
                  number: 80