apiVersion: v1
kind: Service
metadata:
  name: flask-project
spec:
  type: ClusterIP
  selector: ## conecta service com os pods via label
    app: flask-project
  ports:
    - name: http
      port: 80        # porta do service, exposta dentro do cluster
      targetPort: 8080 # porta real do container